// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/stunivoz-prd/AppFlow.tsx": () => import("../components/mockups/stunivoz-prd/AppFlow.tsx"),
  "./components/mockups/stunivoz-prd/PRD.tsx": () => import("../components/mockups/stunivoz-prd/PRD.tsx"),
  "./components/mockups/stunivoz-prd/TechStack.tsx": () => import("../components/mockups/stunivoz-prd/TechStack.tsx"),
  "./components/mockups/stunivoz-prd/UIAudit.tsx": () => import("../components/mockups/stunivoz-prd/UIAudit.tsx"),
  "./components/mockups/stunivoz-prd/WrittenFlow.tsx": () => import("../components/mockups/stunivoz-prd/WrittenFlow.tsx")
};
